use_frameworks!

platform :ios, '13.0'

target 'AudioMetadataParser_Example' do
  pod 'AudioMetadataParser', :path => '../'

  target 'AudioMetadataParser_Tests' do
    inherit! :search_paths
  end
end
